services:
  mysql:
    image: mysql:8.0 
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_books      
      MYSQL_USER: docker              
      MYSQL_PASSWORD: docker      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
